### ISSUE TITLE
hide internal type information?

### ISSUE THREAD

**Issue by hellt** [karimra/gnmiClient#12]
It seems that having the internal type of the value does not benefit the user. Any reasons to keep it?

In the output below I am referring to `(*gnmi.TypedValue_JsonVal)`
```
root@eve-ng:~# gnmiClient -a 10.1.0.11:57400 -u admin -p admin --insecure get --path /state/system/platform
timestamp: 1587670793967241885
prefix:
alias:
state/system/platform: (*gnmi.TypedValue_JsonVal) "7750 SR-1s"
```

**Comment by karimra** [comment]
done, it will show with --debug flag only, in a separate line
