### ISSUE TITLE
consider naming the binary to gnmiclient (all small)

### ISSUE THREAD

**Issue by hellt** [karimra/gnmiClient#40]
it is considered to be a bad practice for a tool binary name to have characters which require <kbd>shift</kbd> press

background: https://smallstep.com/blog/the-poetics-of-cli-command-names/

**Comment by karimra** [comment]
as discussed: gnmic is good

**Comment by hellt** [comment]
@karimra can you rename the repo to `gnmic` as well since the name is settled?

**Comment by karimra** [comment]
I was thinking about doing that.
I will wait until I get some PRs out of the way.
