### ISSUE TITLE
address staticcheck errors

### ISSUE THREAD

**Issue by hellt** [karimra/gnmiClient#56]
I've introduced [staticcheck](https://staticcheck.io/docs/) in Testing pipeline; it found some issues - https://github.com/karimra/gnmiClient/runs/789172646?check_suite_focus=true

- [x] cmd/get.go:148:6: func stringInList is unused (U1000)
- [ ] cmd/root.go:82:4: grpclog.SetLogger is deprecated: use SetLoggerV2.  (SA1019)
- [x] cmd/path.go:58:28: should use make(chan string) instead (S1019)
- [x] cmd/root.go:186:22: grpc.WithTimeout is deprecated: use DialContext instead of Dial and context.WithTimeout instead.  - [ ] Will be supported throughout 1.x.  (SA1019)
- [x] cmd/root.go:368:66: syscall.SIGKILL cannot be trapped (did you mean syscall.SIGTERM?) (SA1016)
- [x] cmd/root.go:418:9: assigning the result of this type assertion to a variable (switch targetsInt := targetsInt.(type)) could eliminate type assertions in switch cases (S1034)
- [x] 	cmd/root.go:420:38: could eliminate this type assertion
- [x] 	cmd/root.go:424:16: could eliminate this type assertion
- [x] cmd/root.go:446:10: assigning the result of this type assertion to a variable (switch t := t.(type)) could eliminate type assertions in switch cases (S1034)
- [x] 	cmd/root.go:448:30: could eliminate this type assertion
- [x] cmd/set.go:189:16: should use String() instead of fmt.Sprintf (S1025)
- [x] cmd/set.go:196:16: should use String() instead of fmt.Sprintf (S1025)
- [x] cmd/subscribe.go:107:7: ineffective break statement. Did you mean to break out of the outer loop? (SA4011)
- [x] cmd/version.go:41:3: redundant return statement (S1023)

**Comment by karimra** [comment]
The standard logger doesn't implement .Error method, so it cannot be used with grpc.SetLoggerV2.
we can move to logrus in the future

**Comment by hellt** [comment]
the only unresolved issue with SetLoggerV2 was silenced and the backlog issue #59 has been created
