### ISSUE TITLE
with a required `--path` flag it is impossible to set paths in a config file

### ISSUE THREAD

**Issue by hellt** [karimra/gnmiClient#62]
Recently we added a requirement condition for `path` cli flags to avoid getting entire state when this flag is missing on the CLI.

But that has a side effect of not being able to set paths in a config file:

```
❯ go run . --config ~/.gnmic.yml get
Error: required flag(s) "path" not set
```

I propose we remove the _required_ condition on the flag and instead check the value of the `paths := viper.GetStringSlice("get-path")` for emptiness

**Comment by karimra** [comment]
Apparently it's a common issue in viper and pflag interactions, found a few workarounds for it. 
Check #63
